language: php

php:
  - 7.0

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env
  - psql -c 'create database forge;' -U postgres
  - php artisan migrate:install --env=testing --no-interaction -vvv

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/codecept run functional
  - php artisan migrate:rollback --env=testing --no-interaction -vvv
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --dry-run --diff
  - vendor/bin/phpunit

notifications:
  email: false
